typedef struct Participante;
typedef struct Temporada;
typedef struct Serie;

int altura_Serie(Serie *s);
int calcularFB_Serie(Serie *s);
void atualizarAltura_Serie(Serie *s);
Serie *rotacaoDireita_Serie(Serie *s);
Serie *rotacaoEsquerda_Serie(Serie *s);
int iniciarS(Serie **s);
void preencherS(Serie **s, int id, char titulo[]);
void mostrarS(Serie *s);
int cadastrarS(Serie **s, Serie *novo);
int validarS(Serie *s, int id);
Serie *buscarS(Serie *s, int id);
int geraId(Serie **s);
void mostrar_all_S(Serie **s);
void liberar_all_P(Participante **p);
void liberar_all_T(Temporada **t);
void liberar_all_S(Serie **s);
int altura_Temporada(Temporada *t);
int calcularFB_Temporada(Temporada *t);
void atualizarAltura_Temporada(Temporada *t);
Temporada *rotacaoDireita_Temporada(Temporada *t);
Temporada *rotacaoEsquerda_Temporada(Temporada **t);
void troca(Participante **a, Participante **b);
void OrdenaAtores(Participante **head);
void cadastran_atores(Participante **l, int n_atores);
void preencherT(Temporada **t, int id);
int cadastrarT(Temporada **t, int id);
void mostrarT(Temporada *t);
Temporada *buscarT(Temporada *t, int id);
void mostrar_all_T(Temporada *t);
void mostrarP(Participante *p);
void mostrar_all_P(Participante *p);
void letra_D(Temporada *t);
